import React, { useState, useEffect } from 'react';
import Icon from '../../../components/AppIcon';

const ActivityFeed = () => {
  const [activities, setActivities] = useState([]);
  const [filter, setFilter] = useState('all');
  const [isAutoRefresh, setIsAutoRefresh] = useState(true);

  const activityTypes = [
    { value: 'all', label: 'All Activities', count: 0 },
    { value: 'system', label: 'System Events', count: 0 },
    { value: 'security', label: 'Security', count: 0 },
    { value: 'performance', label: 'Performance', count: 0 },
    { value: 'user', label: 'User Actions', count: 0 }
  ];

  const initialActivities = [
    {
      id: 1,
      type: 'system',
      severity: 'info',
      title: 'Database Backup Completed',
      description: 'Scheduled backup for Health Department database completed successfully',
      timestamp: new Date(Date.now() - 120000),
      department: 'Health',
      user: 'System',
      details: 'Backup size: 2.3 GB, Duration: 45 minutes'
    },
    {
      id: 2,
      type: 'security',
      severity: 'warning',
      title: 'Multiple Failed Login Attempts',
      description: 'User admin@pwd.gov.in exceeded login attempt limit',
      timestamp: new Date(Date.now() - 300000),
      department: 'PWD',
      user: 'Security Monitor',
      details: 'IP: 192.168.1.45, Attempts: 5, Account locked for 30 minutes'
    },
    {
      id: 3,
      type: 'performance',
      severity: 'critical',
      title: 'High CPU Usage Alert',
      description: 'Server CPU usage exceeded 90% threshold',
      timestamp: new Date(Date.now() - 450000),
      department: 'Education',
      user: 'Performance Monitor',
      details: 'Current usage: 94%, Duration: 12 minutes, Auto-scaling initiated'
    },
    {
      id: 4,
      type: 'user',
      severity: 'info',
      title: 'Report Generated',
      description: 'Monthly performance report generated by District Collector',
      timestamp: new Date(Date.now() - 600000),
      department: 'Administration',
      user: 'collector@district.gov.in',
      details: 'Report type: Cross-departmental analysis, Pages: 45'
    },
    {
      id: 5,
      type: 'system',
      severity: 'info',
      title: 'Data Synchronization',
      description: 'Real-time data sync completed across all departments',
      timestamp: new Date(Date.now() - 750000),
      department: 'All',
      user: 'Data Sync Service',
      details: 'Records synced: 15,847, Conflicts resolved: 3'
    },
    {
      id: 6,
      type: 'security',
      severity: 'info',
      title: 'Security Scan Completed',
      description: 'Weekly vulnerability scan completed with no critical issues',
      timestamp: new Date(Date.now() - 900000),
      department: 'IT Security',
      user: 'Security Scanner',
      details: 'Scanned endpoints: 234, Vulnerabilities: 2 low-risk'
    }
  ];

  useEffect(() => {
    setActivities(initialActivities);
    
    if (isAutoRefresh) {
      const interval = setInterval(() => {
        // Simulate new activities
        const newActivity = generateRandomActivity();
        setActivities(prev => [newActivity, ...prev?.slice(0, 19)]); // Keep last 20
      }, 10000);
      
      return () => clearInterval(interval);
    }
  }, [isAutoRefresh]);

  const generateRandomActivity = () => {
    const types = ['system', 'security', 'performance', 'user'];
    const severities = ['info', 'warning', 'critical'];
    const departments = ['Health', 'Education', 'PWD', 'Rural Development', 'Administration'];
    
    const templates = {
      system: [
        'Service restart completed',
        'Database maintenance finished',
        'Backup process initiated',
        'System update deployed'
      ],
      security: [
        'Firewall rule updated',
        'Access permission modified',
        'Security policy enforced',
        'Audit log reviewed'
      ],
      performance: [
        'Memory usage optimized',
        'Network latency improved',
        'Cache cleared successfully',
        'Performance threshold adjusted'
      ],
      user: [
        'User session started',
        'Document uploaded',
        'Report accessed',
        'Settings modified'
      ]
    };

    const type = types?.[Math.floor(Math.random() * types?.length)];
    const severity = severities?.[Math.floor(Math.random() * severities?.length)];
    const department = departments?.[Math.floor(Math.random() * departments?.length)];
    const title = templates?.[type]?.[Math.floor(Math.random() * templates?.[type]?.length)];

    return {
      id: Date.now(),
      type,
      severity,
      title,
      description: `${title} in ${department} department`,
      timestamp: new Date(),
      department,
      user: type === 'user' ? 'user@dept.gov.in' : 'System',
      details: 'Automated system activity'
    };
  };

  const filteredActivities = activities?.filter(activity => 
    filter === 'all' || activity?.type === filter
  );

  const getSeverityColor = (severity) => {
    switch (severity) {
      case 'critical': return 'text-error';
      case 'warning': return 'text-warning';
      case 'info': return 'text-primary';
      default: return 'text-muted-foreground';
    }
  };

  const getSeverityBg = (severity) => {
    switch (severity) {
      case 'critical': return 'bg-error/10';
      case 'warning': return 'bg-warning/10';
      case 'info': return 'bg-primary/10';
      default: return 'bg-muted';
    }
  };

  const getTypeIcon = (type) => {
    switch (type) {
      case 'system': return 'Server';
      case 'security': return 'Shield';
      case 'performance': return 'Activity';
      case 'user': return 'User';
      default: return 'Info';
    }
  };

  const formatTimestamp = (timestamp) => {
    const now = new Date();
    const diff = Math.floor((now - timestamp) / 1000);
    if (diff < 60) return `${diff}s ago`;
    if (diff < 3600) return `${Math.floor(diff / 60)}m ago`;
    return `${Math.floor(diff / 3600)}h ago`;
  };

  return (
    <div className="bg-card rounded-lg border border-border">
      {/* Header */}
      <div className="p-4 border-b border-border">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-lg font-semibold text-foreground">Real-time Activity Feed</h3>
          <div className="flex items-center space-x-2">
            <button
              onClick={() => setIsAutoRefresh(!isAutoRefresh)}
              className={`flex items-center space-x-2 px-3 py-1 rounded-md text-sm transition-colors ${
                isAutoRefresh 
                  ? 'bg-success text-success-foreground' 
                  : 'bg-muted text-muted-foreground hover:bg-muted/80'
              }`}
            >
              <Icon name={isAutoRefresh ? "Pause" : "Play"} size={14} />
              <span>{isAutoRefresh ? 'Live' : 'Paused'}</span>
            </button>
            <button className="p-2 rounded-md hover:bg-muted transition-colors">
              <Icon name="RefreshCw" size={16} />
            </button>
          </div>
        </div>

        {/* Filter Tabs */}
        <div className="flex space-x-1 bg-muted rounded-lg p-1">
          {activityTypes?.map((type) => (
            <button
              key={type?.value}
              onClick={() => setFilter(type?.value)}
              className={`flex-1 px-3 py-2 rounded-md text-sm font-medium transition-all ${
                filter === type?.value
                  ? 'bg-card text-foreground shadow-sm'
                  : 'text-muted-foreground hover:text-foreground'
              }`}
            >
              {type?.label}
            </button>
          ))}
        </div>
      </div>
      {/* Activity List */}
      <div className="max-h-96 overflow-y-auto">
        {filteredActivities?.length === 0 ? (
          <div className="p-8 text-center text-muted-foreground">
            <Icon name="Activity" size={48} className="mx-auto mb-4 opacity-50" />
            <p>No activities found for the selected filter.</p>
          </div>
        ) : (
          <div className="divide-y divide-border">
            {filteredActivities?.map((activity) => (
              <div key={activity?.id} className="p-4 hover:bg-muted/50 transition-colors">
                <div className="flex items-start space-x-3">
                  <div className={`p-2 rounded-lg ${getSeverityBg(activity?.severity)}`}>
                    <Icon 
                      name={getTypeIcon(activity?.type)} 
                      size={16} 
                      className={getSeverityColor(activity?.severity)}
                    />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center justify-between mb-1">
                      <h4 className="font-medium text-foreground truncate">
                        {activity?.title}
                      </h4>
                      <span className="text-xs text-muted-foreground whitespace-nowrap ml-2">
                        {formatTimestamp(activity?.timestamp)}
                      </span>
                    </div>
                    <p className="text-sm text-muted-foreground mb-2">
                      {activity?.description}
                    </p>
                    <div className="flex items-center justify-between text-xs">
                      <div className="flex items-center space-x-4 text-muted-foreground">
                        <span>Department: {activity?.department}</span>
                        <span>User: {activity?.user}</span>
                      </div>
                      <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                        activity?.severity === 'critical' ? 'bg-error/20 text-error' :
                        activity?.severity === 'warning'? 'bg-warning/20 text-warning' : 'bg-primary/20 text-primary'
                      }`}>
                        {activity?.severity}
                      </span>
                    </div>
                    {activity?.details && (
                      <div className="mt-2 p-2 bg-muted/50 rounded text-xs text-muted-foreground">
                        {activity?.details}
                      </div>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default ActivityFeed;